Есть решения
le1tsova/js-problems pull request #2
Opened 2019-08-16 13:28 UTC by le1tsova

2019-08-21 16:50 UTC, le1tsova commented
@mbelsky, посмотри, пожалуйста

2019-08-22 07:44 UTC, mbelsky commented
![Screenshot 2019-08-22 at 10 42 42](https://user-images.githubusercontent.com/3923527/63495960-9774de00-c4c9-11e9-9a82-2423f3d9a891.png)

Наличие моих коммитов в пр-е говорит о том что ветка solutions не синхронизирована с upstream master. Из-за этого [здесь](https://github.com/le1tsova/js-problems/pull/2/files) отображаются изменения не требующие ревью.

2019-08-22 11:01 UTC, mbelsky requested changes

2019-08-22 11:01 UTC, mbelsky commented on problems/024-timeago.js
> +    if (seconds < 50) {
А что, если секунд 59?

2019-08-22 11:01 UTC, mbelsky commented on problems/024-timeago.js
> +    if (seconds >= 120 && seconds < 1800) {
Какой здесь смысл в `seconds >= 120` и аналогичных проверках ниже?

2019-08-22 11:01 UTC, mbelsky commented on problems/024-timeago.js
> +    if (seconds >= 604800 && seconds < 1209600) {
такие страшные числа положить бы в константы с говорящими именами

2019-08-22 11:01 UTC, mbelsky commented on problems/026-vacation.js
> +    const holidays = new Date(year + "," + month + "," + day);
зачем делать это строкой? посмотри внимательнее на доступные конструкторы у Date

2019-08-22 11:01 UTC, mbelsky commented on problems/026-vacation.js
> +    function formatDate(num) {
зачем эту функцию делать вложенной?

2019-08-22 11:01 UTC, mbelsky commented on problems/027-has.js
> +    for (let i = 0; i < path.length; i++) {
Почему не forEach? 
😭

2019-08-22 19:08 UTC, le1tsova commented on problems/024-timeago.js
> +    return "undefined";
тесты просят

2019-08-27 13:07 UTC, le1tsova commented
@mbelsky , посмотри, пожалуйста

2019-08-27 13:17 UTC, mbelsky commented on problems/024-timeago.js
> +    if (seconds < 86400) {
Надеялся ты и этот ужас спрячешь в константы, и то что ниже

2019-08-27 13:17 UTC, mbelsky commented on problems/024-timeago.js
> +        return "1 day ago";
Нет логики для `2\3 days ago`

2019-08-27 13:17 UTC, mbelsky commented on problems/027-has.js
> +        if (typeof obj !== "object" || obj === null) {
`result` никак не используется

2019-08-27 13:17 UTC, mbelsky commented on problems/028-more-parentheses.js
> +        if (element === "<" || element === "(" || element === "{") {
Тут лучше проверять что element не входит в `Object.keys(parent)`

2019-08-27 13:17 UTC, mbelsky commented on problems/028-more-parentheses.js
> +                stack.splice(stack.lastIndexOf(parent[element]), 1);
Зачем так сложно если есть `.pop()` или тут делается что-то другое?

2019-08-28 09:23 UTC, le1tsova commented on problems/024-timeago.js
> +        return "1 day ago";
Расширь, пожалуйста, тесты

2019-08-28 09:29 UTC, mbelsky approved these changes
Продолжаем работать над названиями переменных и не повторять прошлых ошибок.

Но это пока предлагаю мержить

2019-08-28 09:29 UTC, mbelsky commented on problems/024-timeago.js
> +        return "1 day ago";
Оставим так

2019-08-28 09:29 UTC, mbelsky commented on problems/024-timeago.js
> +    return "undefined";
🐷

2019-08-28 09:29 UTC, mbelsky commented on problems/028-more-parentheses.js
> +        let element = value[i];
const 
😭

2019-08-30 10:31 UTC, merged